/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.daniel.store.view;

import com.daniel.store.dao.DocumentDAO;
import com.daniel.store.dao.SupplierDAO;
import com.daniel.store.entity.Document;
import com.daniel.store.entity.Supplier;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author carri
 */
public class DocumentsUI extends javax.swing.JFrame {

    /**
     * Creates new form DocumentsUI
     */
    public DocumentsUI() {
        initComponents();
        loadDocuments();
        loadSupliers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_Lugar = new javax.swing.JLabel();
        jLabel_Fecha = new javax.swing.JLabel();
        jLabel_MontoAPagar = new javax.swing.JLabel();
        jLabel_FechaAPagar = new javax.swing.JLabel();
        jLabelDatosEmpresa = new javax.swing.JLabel();
        jLabelNombreEmpresa = new javax.swing.JLabel();
        jLabel_DireccionEmpresa = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Lugar = new javax.swing.JTextField();
        jTextField_Fecha = new javax.swing.JTextField();
        jTextField_MontoAPagar = new javax.swing.JTextField();
        jTextField_FechaAPagar = new javax.swing.JTextField();
        jTextField_DireccionEmpresa = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonPagar = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDocumentosPorPagar = new javax.swing.JList<>();
        jComboBoxNameCompany = new javax.swing.JComboBox<>();
        jLabelFondoDePantalla = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitulo.setText("DOCUMENTOS POR PAGAR");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel_ID.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel_ID.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_ID.setText("N:");
        jPanel1.add(jLabel_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jLabel_Lugar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel_Lugar.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_Lugar.setText("Lugar:");
        jPanel1.add(jLabel_Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel_Fecha.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel_Fecha.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_Fecha.setText("Fecha:");
        jPanel1.add(jLabel_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel_MontoAPagar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel_MontoAPagar.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_MontoAPagar.setText("Monto a pagar:");
        jPanel1.add(jLabel_MontoAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel_FechaAPagar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel_FechaAPagar.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_FechaAPagar.setText("Fecha a pagar:");
        jPanel1.add(jLabel_FechaAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabelDatosEmpresa.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelDatosEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDatosEmpresa.setText("Datos de la empresa");
        jPanel1.add(jLabelDatosEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabelNombreEmpresa.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelNombreEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNombreEmpresa.setText("Nombre de la empresa:");
        jPanel1.add(jLabelNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel_DireccionEmpresa.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel_DireccionEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_DireccionEmpresa.setText("Direccion de la empresa:");
        jPanel1.add(jLabel_DireccionEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 360, -1));

        jTextField_Lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LugarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 360, -1));

        jTextField_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FechaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 360, -1));

        jTextField_MontoAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MontoAPagarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_MontoAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 280, -1));

        jTextField_FechaAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FechaAPagarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_FechaAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 360, -1));

        jTextField_DireccionEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DireccionEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_DireccionEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 350, -1));

        jButtonGuardar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 150, 50));

        jButtonLimpiar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 150, 50));

        jButtonPagar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonPagar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 150, 50));

        jLabelTitulo1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitulo1.setText("DOCUMENTOS POR PAGAR");
        jPanel1.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        jListDocumentosPorPagar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDocumentosPorPagarValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListDocumentosPorPagar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 280, -1));

        jComboBoxNameCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNameCompanyActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxNameCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 270, -1));

        jLabelFondoDePantalla.setIcon(new javax.swing.ImageIcon("C:\\Users\\carri\\Downloads\\INTERFAZ\\21423.png")); // NOI18N
        jPanel1.add(jLabelFondoDePantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 953, 519));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_LugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LugarActionPerformed

    private void jTextField_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FechaActionPerformed

    private void jTextField_MontoAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MontoAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MontoAPagarActionPerformed

    private void jTextField_FechaAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FechaAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FechaAPagarActionPerformed

    private void jTextField_DireccionEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DireccionEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DireccionEmpresaActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
     Document document=new Document();
     int idDocumento = Integer.parseInt(this.jTextField_ID.getText());
     document.setDocumentsId(idDocumento);
     String site= this.jTextField_Lugar.getText();
     document.setSite(site);
     document.setSupplierId(1);
     
     float price=Float.parseFloat(this.jTextField_MontoAPagar.getText());
     document.setAmountPay(price);
     String siteCompany=this.jTextField_DireccionEmpresa.getText();
     document.setSiteCompany(siteCompany);
     
    try {
        String dateString = this.jTextField_Fecha.getText();
        long time;
        time = new SimpleDateFormat("dd-MM-yyyy").parse(dateString).getTime();
        document.setDate(new Date(time));
    } catch (ParseException ex) {
        Logger.getLogger(DocumentsUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    try {
        String dateString = this.jTextField_FechaAPagar.getText();
        long time;
        time = new SimpleDateFormat("dd-MM-yyyy").parse(dateString).getTime();
        document.setDatePay(new Date(time));
    } catch (ParseException ex) {
        Logger.getLogger(DocumentsUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
        System.out.println(document);
        
        boolean saved = documentDao.setProductToDB(document);
        if(saved){
            JOptionPane.showMessageDialog(null, "Documento guardado", "Documentos", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "ERROR: Documento No Guardado", "Documentos", JOptionPane.INFORMATION_MESSAGE);
        }

     
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextField_DireccionEmpresa.setText("");
        jTextField_Fecha.setText(" ");
        jTextField_FechaAPagar.setText(" ");
        jTextField_ID.setText(" ");
        jTextField_Lugar.setText(" ");
        jTextField_MontoAPagar.setText(" ");
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jComboBoxNameCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNameCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNameCompanyActionPerformed

    private void jListDocumentosPorPagarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDocumentosPorPagarValueChanged
       
         Document selectedDocument = null;
        if(!evt.getValueIsAdjusting()){
            JList lsm = (javax.swing.JList)evt.getSource();
            int index = lsm.getSelectedIndex();
            selectedDocument = documents.get(index);
            System.out.println(index + ": " + selectedDocument);
        }       
        
        if(selectedDocument!=null){
            this.jTextField_ID.setText(String.valueOf(selectedDocument.getDocumentsId()));
            this.jTextField_Lugar.setText(selectedDocument.getSite());
            this.jTextField_Fecha.setText(String.valueOf(selectedDocument.getDate()));
            this.jTextField_MontoAPagar.setText(String.valueOf(selectedDocument.getAmountPay()));
            this.jTextField_FechaAPagar.setText(String.valueOf(selectedDocument.getDatePay()));
            this.jTextField_DireccionEmpresa.setText(selectedDocument.getSiteCompany());

            

        }
    }//GEN-LAST:event_jListDocumentosPorPagarValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JComboBox<String> jComboBoxNameCompany;
    private javax.swing.JLabel jLabelDatosEmpresa;
    private javax.swing.JLabel jLabelFondoDePantalla;
    private javax.swing.JLabel jLabelNombreEmpresa;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabel_DireccionEmpresa;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_FechaAPagar;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Lugar;
    private javax.swing.JLabel jLabel_MontoAPagar;
    private javax.swing.JList<String> jListDocumentosPorPagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_DireccionEmpresa;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_FechaAPagar;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Lugar;
    private javax.swing.JTextField jTextField_MontoAPagar;
    // End of variables declaration//GEN-END:variables
 DefaultListModel documentsModel = new DefaultListModel();
    DocumentDAO documentDao = new DocumentDAO();
    List<Document> documents = new ArrayList<>();
    List<String> documentsDescription = new ArrayList<>();

    private void loadDocuments() {
        jListDocumentosPorPagar.setModel(documentsModel);
        documents = documentDao.getAllDocumentFromDB();

        for (Document p : documents) {
            documentsDescription.add(p.getSupplierId() + " - " + p.getSite() + " - " + p.getDate()+ " - "+ p.getAmountPay()+ " - "+ p.getDatePay()+ " - "+ p.getSiteCompany());
        }

        documentsModel.addAll(documentsDescription);
    }

   /** DefaultListModel supplierModel = new DefaultListModel();
    SupplierDAO supplierDao = new SupplierDAO();
    List<Supplier> suppliers;
    List<String> suppliersDescription = new ArrayList<>();

    private void loadSuppliers() {
        jComboBoxNameCompany.setModel();
        suppliers = supplierDao.getAllSupplierFromDB();

        for (Supplier p : suppliers) {
            suppliersDescription.add(p.getSupplierId() + " - " + p.getName());
        }

        supplierModel.addAll(suppliersDescription);
    }*/
    
    SupplierDAO supplierDao = new SupplierDAO();
    List<Supplier> suppliers;
    List<String> suppliersDescription = new ArrayList<>();
        
    private void loadSupliers(){
        suppliers = supplierDao.getAllSupplierFromDB();
        
         for(Supplier p :suppliers ){
             suppliersDescription.add(p.getName());
         }
         
        jComboBoxNameCompany.setModel(new DefaultComboBoxModel<>(suppliersDescription.toArray(String[]::new)));

    }
}
