/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.daniel.store.view;

/**
 *
 * @author carri
 */
public class FacturaUI extends javax.swing.JFrame {

    /**
     * Creates new form FacturaUI
     */
    public FacturaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFacturaA = new javax.swing.JLabel();
        jLabelEnviarA = new javax.swing.JLabel();
        jLabelDireccionComprador = new javax.swing.JLabel();
        jLabelN_Factura = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelRFC = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FACTURA");

        jLabelFacturaA.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelFacturaA.setText("Facturar a:");

        jLabelEnviarA.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelEnviarA.setText("Enviar a:");

        jLabelDireccionComprador.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelDireccionComprador.setText("Direccion Del Comprador:");

        jLabelN_Factura.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelN_Factura.setText("N DE FACTURA#");

        jLabelFecha.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelFecha.setText("Fecha de:");

        jLabelRFC.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelRFC.setText("RFC:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelFacturaA)
                    .addComponent(jLabelN_Factura)
                    .addComponent(jLabelEnviarA)
                    .addComponent(jLabelDireccionComprador)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRFC)
                            .addComponent(jLabelFecha))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabelFacturaA)
                .addGap(34, 34, 34)
                .addComponent(jLabelDireccionComprador)
                .addGap(34, 34, 34)
                .addComponent(jLabelEnviarA)
                .addGap(34, 34, 34)
                .addComponent(jLabelN_Factura)
                .addGap(35, 35, 35)
                .addComponent(jLabelRFC)
                .addGap(32, 32, 32)
                .addComponent(jLabelFecha)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDireccionComprador;
    private javax.swing.JLabel jLabelEnviarA;
    private javax.swing.JLabel jLabelFacturaA;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelN_Factura;
    private javax.swing.JLabel jLabelRFC;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
