/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.daniel.store.view;

import com.daniel.store.dao.ProductDAO;
import com.daniel.store.entity.Product;
import java.util.List;

/**
 *
 * @author carri
 */
public class ProductsUI extends javax.swing.JFrame {

    /**
     * Creates new form Producto1Paletas
     */
    public ProductsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelProductos = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelNota = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldNota = new javax.swing.JTextField();
        jLabelTituloTabla = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        jLabelFondo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelProductos.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 160, 50));

        jButtonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelProductos.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 160, 50));

        jButtonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelProductos.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 160, 50));

        jLabelTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitulo.setText("PRODUCTOS");
        jPanelProductos.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jLabelNombre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNombre.setText("Nombre:");
        jPanelProductos.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabelMarca.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelMarca.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMarca.setText("Marca:");
        jPanelProductos.add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabelPrecio.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(102, 102, 102));
        jLabelPrecio.setText("Nota:");
        jPanelProductos.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jLabelNota.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelNota.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNota.setText("Precio:");
        jPanelProductos.add(jLabelNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanelProductos.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 470, -1));

        jTextFieldMarca.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldMarca.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        jPanelProductos.add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 470, -1));

        jTextFieldPrecio.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldPrecio.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jPanelProductos.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 470, 50));

        jTextFieldNota.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldNota.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaActionPerformed(evt);
            }
        });
        jPanelProductos.add(jTextFieldNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 470, -1));

        jLabelTituloTabla.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTituloTabla.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTabla.setText("PRODUCTOS");
        jPanelProductos.add(jLabelTituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));

        jListProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListProductos);

        jPanelProductos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 200, 330));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\carri\\Downloads\\INTERFAZ\\21423.png")); // NOI18N
        jLabelFondo.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                jLabelFondoAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        jPanelProductos.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1117, 585));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jLabelFondoAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabelFondoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoAncestorMoved

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNota;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloTabla;
    private javax.swing.JList<String> jListProductos;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNota;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables

}
