/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.daniel.store.view;

import com.daniel.store.dao.ProductDAO;
import com.daniel.store.dao.SaleProductDAO;
import com.daniel.store.entity.Product;
import com.daniel.store.entity.SaleProduct;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author carri
 */
public class SaleProductsUI extends javax.swing.JFrame {

    /**
     * Creates new form VentasUI
     */
    public SaleProductsUI() {
        initComponents();
        loadSales();
        loadSaleProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonPagar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelProductoID = new javax.swing.JLabel();
        jLabelPrecioUnidad = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelTituloTablaInventario = new javax.swing.JLabel();
        jLabelTituloTablaCarrito = new javax.swing.JLabel();
        jTextFieldProductoID = new javax.swing.JTextField();
        jTextFieldPrecioUnidad = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInventario = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCarrito = new javax.swing.JList<>();
        jLabelFondoPantalla = new javax.swing.JLabel();

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonAgregar.setText("Guardar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 160, 50));

        jButtonRemover.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRemover.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel.add(jButtonRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 160, 50));

        jButtonPagar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPagar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 160, 50));

        jLabelTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitulo.setText("VENTAS");
        jPanel.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jLabelProductoID.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelProductoID.setForeground(new java.awt.Color(102, 102, 102));
        jLabelProductoID.setText("Producto ID:");
        jPanel.add(jLabelProductoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabelPrecioUnidad.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelPrecioUnidad.setForeground(new java.awt.Color(102, 102, 102));
        jLabelPrecioUnidad.setText("Precio Unidad:");
        jPanel.add(jLabelPrecioUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCantidad.setText("Cantidad:");
        jPanel.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabelTituloTablaInventario.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTituloTablaInventario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTablaInventario.setText("INVENTARIO");
        jPanel.add(jLabelTituloTablaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, -1));

        jLabelTituloTablaCarrito.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTituloTablaCarrito.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTablaCarrito.setText("CARRITO");
        jPanel.add(jLabelTituloTablaCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 160, -1));

        jTextFieldProductoID.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldProductoID.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldProductoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductoIDActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldProductoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 380, -1));

        jTextFieldPrecioUnidad.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldPrecioUnidad.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPrecioUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioUnidadActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldPrecioUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 380, -1));

        jTextFieldCantidad.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 380, -1));

        jListInventario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListInventario);

        jPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 330));

        jListCarrito.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListCarrito);

        jPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 200, 330));

        jLabelFondoPantalla.setIcon(new javax.swing.ImageIcon("C:\\Users\\carri\\Downloads\\INTERFAZ\\21423.png")); // NOI18N
        jPanel.add(jLabelFondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1117, 666));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        SeleccionDeTicketFacturaUI seleccionUI = new SeleccionDeTicketFacturaUI ();
        seleccionUI.setVisible(true);
        seleccionUI.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        SaleProduct saleProductUi=new SaleProduct();
        int productId= Integer.parseInt (this.jTextFieldProductoID.getText());
        saleProductUi.setProductId(productId);
        int cantidad= Integer.parseInt(this.jTextFieldCantidad.getText());
        saleProductUi.setAmount(cantidad);
        float precioUnidad= Float.parseFloat(this.jTextFieldPrecioUnidad.getText());
        saleProductUi.setUnitPrice(precioUnidad);
        saleProductUi.setSaleProductId(1);
        saleProductUi.setSaleId(1);
        System.out.println(saleProductUi);
        
        boolean saved=  saleProductDao.setSaleProductToDB(saleProductUi);
        if(saved){
            JOptionPane.showMessageDialog(null, "Venta Guardada", "Ventas", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "ERROR: Venta No Guardada", "Ventas", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextFieldProductoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductoIDActionPerformed

    private void jTextFieldPrecioUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioUnidadActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelFondoPantalla;
    private javax.swing.JLabel jLabelPrecioUnidad;
    private javax.swing.JLabel jLabelProductoID;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloTablaCarrito;
    private javax.swing.JLabel jLabelTituloTablaInventario;
    private javax.swing.JList<String> jListCarrito;
    private javax.swing.JList<String> jListInventario;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldPrecioUnidad;
    private javax.swing.JTextField jTextFieldProductoID;
    // End of variables declaration//GEN-END:variables
 DefaultListModel productsModel = new DefaultListModel();
    ProductDAO SaleproductDao = new ProductDAO();
    List<Product> products;
    List<String> prodcutsDescription = new ArrayList<>();
        
    private void loadSales() {
        jListInventario.setModel(productsModel);
        products = SaleproductDao.getAllProductsFromDB();
        
         for(Product p : products){
             prodcutsDescription.add("ID producto " +p.getProductId() + "-" + p.getName()+ " -Inventario " + p.getStock()+ " -Precio " + p.getPrice());
         }
         
        productsModel.addAll(prodcutsDescription);
    }
    
    DefaultListModel salesproductsModel = new DefaultListModel();
    SaleProductDAO saleProductDao = new SaleProductDAO();
    List<SaleProduct> saleProducts;
    List<String> salesProductsDescription = new ArrayList<>();
        
    private void loadSaleProducts() {
        jListCarrito.setModel(salesproductsModel);
        saleProducts = saleProductDao.getAllSaleProductFromDB();
        
         for(SaleProduct a : saleProducts){
             salesProductsDescription.add( " ID Producto " + a.getProductId() + " -Cantidad " + a.getAmount() + " -$ " + a.getUnitPrice());
         }
         
        salesproductsModel.addAll(salesProductsDescription);
    }
    
}
