/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.daniel.store.view;

import com.daniel.store.dao.ProductDAO;
import com.daniel.store.dao.SaleProductDAO;
import com.daniel.store.entity.Product;
import com.daniel.store.entity.SaleProduct;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author carri
 */
public class SaleProductsUI extends javax.swing.JFrame {

    /**
     * Creates new form VentasUI
     */
    public SaleProductsUI() {
        initComponents();
        //loadSales();
        //loadSaleProducts();
        loadProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonPagar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelProductoID = new javax.swing.JLabel();
        jLabelPrecioUnidad = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelTituloTablaInventario = new javax.swing.JLabel();
        jLabelTituloTablaCarrito = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabelProductoID1 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldPSubtotal = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelPrecioUnidad1 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInventario = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCarrito = new javax.swing.JList<>();
        jLabelFondoPantalla = new javax.swing.JLabel();

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 160, 50));

        jButtonRemover.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRemover.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonRemover.setText("Limpiar");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel.add(jButtonRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 160, 50));

        jButtonPagar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPagar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 160, 50));

        jLabelTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitulo.setText("VENTAS");
        jPanel.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jLabelProductoID.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelProductoID.setForeground(new java.awt.Color(102, 102, 102));
        jLabelProductoID.setText("Producto:");
        jPanel.add(jLabelProductoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabelPrecioUnidad.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelPrecioUnidad.setForeground(new java.awt.Color(102, 102, 102));
        jLabelPrecioUnidad.setText("Subtotal:");
        jPanel.add(jLabelPrecioUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCantidad.setText("Cantidad:");
        jPanel.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabelTituloTablaInventario.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTituloTablaInventario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTablaInventario.setText("INVENTARIO");
        jPanel.add(jLabelTituloTablaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, -1));

        jLabelTituloTablaCarrito.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelTituloTablaCarrito.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTablaCarrito.setText("CARRITO");
        jPanel.add(jLabelTituloTablaCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 160, -1));

        jTextFieldPrice.setEditable(false);
        jTextFieldPrice.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldPrice.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPrice.setEnabled(false);
        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 380, -1));

        jLabelProductoID1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelProductoID1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelProductoID1.setText("Precio Unidad:");
        jPanel.add(jLabelProductoID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jTextFieldProductName.setEditable(false);
        jTextFieldProductName.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldProductName.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldProductName.setEnabled(false);
        jTextFieldProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductNameActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 380, -1));

        jTextFieldPSubtotal.setEditable(false);
        jTextFieldPSubtotal.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldPSubtotal.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPSubtotal.setEnabled(false);
        jTextFieldPSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPSubtotalActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldPSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 380, -1));

        jTextFieldCantidad.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 380, -1));

        jLabelPrecioUnidad1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelPrecioUnidad1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelPrecioUnidad1.setText("Total:");
        jPanel.add(jLabelPrecioUnidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTotal.setEnabled(false);
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        jPanel.add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 380, -1));

        jListInventario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListInventario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListInventarioValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListInventario);

        jPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 330));

        jListCarrito.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListCarrito);

        jPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 200, 330));

        jLabelFondoPantalla.setIcon(new javax.swing.ImageIcon("C:\\Users\\carri\\Downloads\\INTERFAZ\\21423.png")); // NOI18N
        jPanel.add(jLabelFondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1117, 666));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
       jTextFieldCantidad.setText(" ");
    jTextFieldPSubtotal.setText(" ");
    jTextFieldProductName.setText(" ");
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        SeleccionDeTicketFacturaUI seleccionUI = new SeleccionDeTicketFacturaUI ();
        seleccionUI.setVisible(true);
        seleccionUI.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButtonPagarActionPerformed

    //Guardar ID de la venta actual.
    Integer saleId = null;
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        
        SaleProduct saleProductUi=new SaleProduct();
        int productId= Integer.parseInt (this.jTextFieldProductName.getText());
        saleProductUi.setProductId(productId);
        int cantidad= Integer.parseInt(this.jTextFieldCantidad.getText());
        saleProductUi.setAmount(cantidad);
        float precioUnidad= Float.parseFloat(this.jTextFieldPSubtotal.getText());
        saleProductUi.setUnitPrice(precioUnidad);
        saleProductUi.setSaleProductId(1);
        saleProductUi.setSaleId(1);
        System.out.println(saleProductUi);
        
        boolean saved=  saleProductDao.setSaleProductToDB(saleProductUi);
        if(saved){
            JOptionPane.showMessageDialog(null, "Venta Guardada", "Ventas", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "ERROR: Venta No Guardada", "Ventas", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextFieldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameActionPerformed

    private void jTextFieldPSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPSubtotalActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jListInventarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListInventarioValueChanged
        // TODO add your handling code here:
        Product selectedProduct = null;
        if(!evt.getValueIsAdjusting()){
            JList lsm = (javax.swing.JList)evt.getSource();
            int index = lsm.getSelectedIndex();
            selectedProduct = products.get(index);
            System.out.println(index + ": " + selectedProduct);
        }       
        
        if(selectedProduct!=null){
            this.jTextFieldProductName.setText(selectedProduct.getName());
            this.jTextFieldPrice.setText(String.valueOf(selectedProduct.getPrice()));

        }
    }//GEN-LAST:event_jListInventarioValueChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelFondoPantalla;
    private javax.swing.JLabel jLabelPrecioUnidad;
    private javax.swing.JLabel jLabelPrecioUnidad1;
    private javax.swing.JLabel jLabelProductoID;
    private javax.swing.JLabel jLabelProductoID1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloTablaCarrito;
    private javax.swing.JLabel jLabelTituloTablaInventario;
    private javax.swing.JList<String> jListCarrito;
    private javax.swing.JList<String> jListInventario;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldPSubtotal;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
 
    
    DefaultListModel productsModel = new DefaultListModel();
    ProductDAO productDAO = new ProductDAO();
    
    //Productos de la base de datos
    List<Product> products = new ArrayList<>();
    //Dexriociones para mostrar al usaurio en la lista
    List<String> prodcutsDescription = new ArrayList<>();
    
    //Cargar los productos disponibles para vender
    private void loadProducts() {
        jListInventario.setModel(productsModel);
        products = productDAO.getAllAvailableProductsFromDB();
        
        for(Product p : products){
            prodcutsDescription.add( p.getName()+ " - Inventario " + p.getStock()+ " - Precio " + p.getPrice());
        }
        productsModel.addAll(prodcutsDescription);
    }
    
    /*private void registerEventListener(){
        ListSelectionModel listSelectionModel = jListInventario.getSelectionModel();
        listSelectionModel.addListSelectionListener(
                            new SharedListSelectionHandler())
            }*/
        
    private void loadSales() {
        jListInventario.setModel(productsModel);
        products = productDAO.getAllProductsFromDB();
        
         for(Product p : products){
             prodcutsDescription.add("ID producto " +p.getProductId() + "-" + p.getName()+ " -Inventario " + p.getStock()+ " -Precio " + p.getPrice());
         }
         
        productsModel.addAll(prodcutsDescription);
    }
    
    DefaultListModel salesproductsModel = new DefaultListModel();
    SaleProductDAO saleProductDao = new SaleProductDAO();
    List<SaleProduct> saleProducts;
    List<String> salesProductsDescription = new ArrayList<>();
        
    private void loadSaleProducts() {
        jListCarrito.setModel(salesproductsModel);
        saleProducts = saleProductDao.getAllSaleProductFromDB();
        
         for(SaleProduct a : saleProducts){
             salesProductsDescription.add( " ID Producto " + a.getProductId() + " -Cantidad " + a.getAmount() + " -$ " + a.getUnitPrice());
         }
         
        salesproductsModel.addAll(salesProductsDescription);
    }
    
}
